const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,PUT,OPTIONS'}});

async function supabase(env,path,init={}){const r=await fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation',...(init.headers||{})}});const text=await r.text();let data=null;try{data=JSON.parse(text)}catch{};return {ok:r.ok,status:r.status,data};}
async function auth(req,env){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;const token=h.slice(7);try{const [h64,p64,s64]=token.split('.');const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(env.JWT_SECRET),{name:'HMAC',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(s64.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),enc.encode(`${h64}.${p64}`));if(!valid)return null;return JSON.parse(atob(p64.replace(/-/g,'+').replace(/_/g,'/')))}catch{return null}}
function b64url(v){return btoa(String.fromCharCode(...new Uint8Array(v))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function jwt(payload,secret){const enc=new TextEncoder();const head=b64url(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'})));const body=b64url(enc.encode(payload));const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(`${head}.${body}`));return `${head}.${body}.${b64url(sig)}`}

export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,PUT,OPTIONS'}});const u=new URL(req.url);try{
 if(u.pathname==='/api/health')return json({ok:true,service:'english-ai-backend',environment:env.ENVIRONMENT||'production',database:Boolean(env.SUPABASE_URL)});
 if(u.pathname==='/api/auth/guest'&&req.method==='POST'){const id=crypto.randomUUID();const user={id,email:null,guest:true,created_at:new Date().toISOString()};const token=await jwt({sub:id,guest:true,iat:Math.floor(Date.now()/1000)},env.JWT_SECRET);if(env.SUPABASE_URL)await supabase(env,'profiles',{method:'POST',body:JSON.stringify({user_id:id,email:null})});return json({user,token})}
 const user=await auth(req,env);if(!user)return json({error:'Authentication required'},401);
 if(u.pathname==='/api/me')return json({user:{id:user.sub,guest:Boolean(user.guest)}});
 if(u.pathname.startsWith('/api/progress/')){const pair=decodeURIComponent(u.pathname.split('/').pop());if(req.method==='GET'){const r=await supabase(env,`progress?user_id=eq.${user.sub}&language_pair=eq.${encodeURIComponent(pair)}`);return json({progress:r.data?.[0]?.data||{pair,xp:0,streak:0,completed:[],mistakes:0,mastery:{}}})}if(req.method==='PUT'){const body=await req.json();const value={pair,xp:Number(body.xp||0),streak:Number(body.streak||0),completed:Array.isArray(body.completed)?body.completed:[],mistakes:Number(body.mistakes||0),mastery:body.mastery||{},updated_at:new Date().toISOString()};const r=await supabase(env,'progress',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:user.sub,language_pair:pair,data:value,updated_at:value.updated_at})});return json({ok:r.ok,progress:value},r.ok?200:500)}}
 if(u.pathname==='/api/leaderboard'&&req.method==='GET'){const r=await supabase(env,'leaderboard_scores?select=user_id,display_name,xp&order=xp.desc&limit=100');return json({entries:r.data||[]})}
 if(u.pathname==='/api/leaderboard/score'&&req.method==='POST'){const body=await req.json();const value={user_id:user.sub,display_name:String(body.name||'Player').slice(0,40),xp:Math.max(0,Number(body.xp||0)),updated_at:new Date().toISOString()};const r=await supabase(env,'leaderboard_scores',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(value)});return json({ok:r.ok,entry:value},r.ok?200:500)}
 return json({error:'Not found'},404);
 }catch(e){return json({error:'Server error',message:String(e.message||e)},500)}}};
