import { LANGUAGE_CATALOG } from './engine/course-engine';

// UI localization is intentionally independent from the learning language.
// Missing strings fall back to English so a new language can be added safely.
const EN = {
  home:'Home',course:'Course',ai:'AI',profile:'Profile',languages:'Languages',
  iSpeak:'I speak',learning:'I want to learn',interfaceLanguage:'Interface language',
  start:'Start',continue:'Continue',next:'Next exercise',finish:'Finish lesson',
  lesson:'Lesson',lessons:'lessons',free:'FREE',allLevels:'All levels are open',
  progress:'My progress',completed:'Completed',mistakes:'Mistakes',streak:'Streak',xp:'XP',
  settings:'Settings',changeLanguage:'Change language',nativeLanguage:'Native language',
  learningLanguage:'Learning language',chooseInterface:'Choose interface language',
  deviceLanguage:'Device language',auto:'Automatic',withoutRegistration:'No registration required',
  freeLearning:'All core lessons are free',aiTutor:'AI Tutor',practice:'Practice',
  correct:'Correct!',almost:'Almost!',rightAnswer:'Correct answer',great:'Great!',
  reset:'Reset progress',freePlan:'Free plan',premium:'Premium',noAds:'No ads',
  extendedAI:'Extended AI Tutor',offline:'Offline learning',statistics:'Advanced statistics',
  competitions:'Competitions',leaderboard:'Leaderboard',achievements:'Achievements',
  chooseLanguages:'Choose your languages',interfaceHint:'The interface follows your chosen language.',
  nativeHint:'Explanations and translations use this language.',learningHint:'Lessons and exercises use this language.',
  startLearning:'Start learning',global:'One app — the whole world',
  noAccount:'Start instantly. Create an account only when you want sync and competitions.',
  freeForever:'Core learning stays free.',chatPlaceholder:'Write in the learning language...'
};

const DICT = {
  en: EN,
  uk: {home:'Головна',course:'Курс',ai:'AI',profile:'Профіль',languages:'Мови',iSpeak:'Я знаю',learning:'Хочу вивчати',interfaceLanguage:'Мова інтерфейсу',start:'Почати',continue:'Продовжити',next:'Наступна вправа',finish:'Завершити урок',lesson:'Урок',lessons:'уроків',free:'БЕЗКОШТОВНО',allLevels:'Усі рівні відкриті',progress:'Мій прогрес',completed:'Завершено',mistakes:'Помилки',streak:'Серія',xp:'XP',settings:'Налаштування',changeLanguage:'Змінити мову',nativeLanguage:'Рідна мова',learningLanguage:'Мова навчання',chooseInterface:'Оберіть мову інтерфейсу',deviceLanguage:'Мова пристрою',auto:'Автоматично',withoutRegistration:'Без обовʼязкової реєстрації',freeLearning:'Усі основні уроки безкоштовні',aiTutor:'AI-репетитор',practice:'Практика',correct:'Правильно!',almost:'Майже!',rightAnswer:'Правильна відповідь',great:'Чудово!',reset:'Скинути прогрес',freePlan:'Безкоштовний план',premium:'Premium',noAds:'Без реклами',extendedAI:'Розширений AI-репетитор',offline:'Навчання офлайн',statistics:'Розширена статистика',competitions:'Змагання',leaderboard:'Таблиця лідерів',achievements:'Досягнення',chooseLanguages:'Оберіть мови',interfaceHint:'Інтерфейс використовує вибрану мову.',nativeHint:'Пояснення та переклади використовують цю мову.',learningHint:'Уроки та вправи використовують цю мову.',startLearning:'Почати навчання',global:'Один застосунок — весь світ',noAccount:'Почніть одразу. Акаунт потрібен лише для синхронізації та змагань.',freeForever:'Основне навчання залишається безкоштовним.',chatPlaceholder:'Напишіть мовою навчання...'},
  pl: {home:'Strona główna',course:'Kurs',ai:'AI',profile:'Profil',languages:'Języki',iSpeak:'Mówię',learning:'Chcę się uczyć',interfaceLanguage:'Język interfejsu',start:'Start',continue:'Dalej',next:'Następne ćwiczenie',finish:'Zakończ lekcję',lesson:'Lekcja',lessons:'lekcji',free:'BEZPŁATNIE',allLevels:'Wszystkie poziomy otwarte',progress:'Mój postęp',completed:'Ukończone',mistakes:'Błędy',streak:'Seria',xp:'XP',settings:'Ustawienia',changeLanguage:'Zmień język',nativeLanguage:'Język ojczysty',learningLanguage:'Język nauki',chooseInterface:'Wybierz język interfejsu',deviceLanguage:'Język urządzenia',auto:'Automatycznie',withoutRegistration:'Bez obowiązkowej rejestracji',freeLearning:'Wszystkie podstawowe lekcje są bezpłatne',aiTutor:'AI Tutor',practice:'Ćwiczenia',correct:'Dobrze!',almost:'Prawie!',rightAnswer:'Poprawna odpowiedź',great:'Świetnie!',reset:'Resetuj postęp',freePlan:'Plan bezpłatny',premium:'Premium',noAds:'Bez reklam',extendedAI:'Rozszerzony AI Tutor',offline:'Nauka offline',statistics:'Rozszerzone statystyki',competitions:'Rywalizacja',leaderboard:'Ranking',achievements:'Osiągnięcia',chooseLanguages:'Wybierz języki',interfaceHint:'Interfejs używa wybranego języka.',nativeHint:'Wyjaśnienia i tłumaczenia używają tego języka.',learningHint:'Lekcje i ćwiczenia używają tego języka.',startLearning:'Rozpocznij naukę',global:'Jedna aplikacja — cały świat',noAccount:'Zacznij od razu. Konto jest potrzebne tylko do synchronizacji i rywalizacji.',freeForever:'Podstawowa nauka pozostaje bezpłatna.',chatPlaceholder:'Napisz w języku nauki...'},
  de: {home:'Startseite',course:'Kurs',ai:'KI',profile:'Profil',languages:'Sprachen',iSpeak:'Ich spreche',learning:'Ich möchte lernen',interfaceLanguage:'Oberflächensprache',start:'Start',continue:'Weiter',next:'Nächste Übung',finish:'Lektion beenden',lesson:'Lektion',lessons:'Lektionen',free:'KOSTENLOS',allLevels:'Alle Stufen offen',progress:'Mein Fortschritt',completed:'Abgeschlossen',mistakes:'Fehler',streak:'Serie',xp:'XP',settings:'Einstellungen',changeLanguage:'Sprache ändern',nativeLanguage:'Muttersprache',learningLanguage:'Lernsprache',chooseInterface:'Oberflächensprache wählen',deviceLanguage:'Gerätesprache',auto:'Automatisch',withoutRegistration:'Keine Registrierung erforderlich',freeLearning:'Alle grundlegenden Lektionen sind kostenlos',aiTutor:'KI-Tutor',practice:'Üben',correct:'Richtig!',almost:'Fast!',rightAnswer:'Richtige Antwort',great:'Sehr gut!',reset:'Fortschritt zurücksetzen',freePlan:'Kostenloser Plan',premium:'Premium',noAds:'Werbefrei',extendedAI:'Erweiterter KI-Tutor',offline:'Offline lernen',statistics:'Erweiterte Statistik',competitions:'Wettbewerbe',leaderboard:'Rangliste',achievements:'Erfolge',chooseLanguages:'Sprachen auswählen',interfaceHint:'Die Oberfläche verwendet die gewählte Sprache.',nativeHint:'Erklärungen und Übersetzungen verwenden diese Sprache.',learningHint:'Lektionen und Übungen verwenden diese Sprache.',startLearning:'Lernen beginnen',global:'Eine App — die ganze Welt',noAccount:'Sofort starten. Ein Konto ist nur für Synchronisierung und Wettbewerbe nötig.',freeForever:'Das Kernlernen bleibt kostenlos.',chatPlaceholder:'In der Lernsprache schreiben...'},
  fr: {home:'Accueil',course:'Cours',ai:'IA',profile:'Profil',languages:'Langues',iSpeak:'Je parle',learning:"Je veux apprendre",interfaceLanguage:"Langue de l'interface",start:'Commencer',continue:'Continuer',next:'Exercice suivant',finish:'Terminer la leçon',lesson:'Leçon',lessons:'leçons',free:'GRATUIT',allLevels:'Tous les niveaux sont ouverts',progress:'Ma progression',completed:'Terminées',mistakes:'Erreurs',streak:'Série',xp:'XP',settings:'Paramètres',changeLanguage:'Changer de langue',nativeLanguage:'Langue maternelle',learningLanguage:"Langue d'apprentissage",chooseInterface:"Choisir la langue de l'interface",deviceLanguage:'Langue de l’appareil',auto:'Automatique',withoutRegistration:'Aucune inscription obligatoire',freeLearning:'Toutes les leçons principales sont gratuites',aiTutor:'Tuteur IA',practice:'Pratique',correct:'Correct !',almost:'Presque !',rightAnswer:'Bonne réponse',great:'Bravo !',reset:'Réinitialiser la progression',freePlan:'Plan gratuit',premium:'Premium',noAds:'Sans publicité',extendedAI:'Tuteur IA avancé',offline:'Apprentissage hors ligne',statistics:'Statistiques avancées',competitions:'Compétitions',leaderboard:'Classement',achievements:'Succès',chooseLanguages:'Choisissez vos langues',interfaceHint:"L'interface utilise la langue choisie.",nativeHint:'Les explications et traductions utilisent cette langue.',learningHint:'Les leçons et exercices utilisent cette langue.',startLearning:"Commencer l'apprentissage",global:'Une application — le monde entier',noAccount:'Commencez immédiatement. Un compte est nécessaire uniquement pour la synchronisation et les compétitions.',freeForever:"L'apprentissage principal reste gratuit.",chatPlaceholder:"Écrivez dans la langue d'apprentissage..."},
  es: {home:'Inicio',course:'Curso',ai:'IA',profile:'Perfil',languages:'Idiomas',iSpeak:'Hablo',learning:'Quiero aprender',interfaceLanguage:'Idioma de la interfaz',start:'Empezar',continue:'Continuar',next:'Siguiente ejercicio',finish:'Terminar lección',lesson:'Lección',lessons:'lecciones',free:'GRATIS',allLevels:'Todos los niveles abiertos',progress:'Mi progreso',completed:'Completadas',mistakes:'Errores',streak:'Racha',xp:'XP',settings:'Ajustes',changeLanguage:'Cambiar idioma',nativeLanguage:'Idioma nativo',learningLanguage:'Idioma de aprendizaje',chooseInterface:'Elige el idioma de la interfaz',deviceLanguage:'Idioma del dispositivo',auto:'Automático',withoutRegistration:'Sin registro obligatorio',freeLearning:'Todas las lecciones principales son gratis',aiTutor:'Tutor de IA',practice:'Práctica',correct:'¡Correcto!',almost:'¡Casi!',rightAnswer:'Respuesta correcta',great:'¡Genial!',reset:'Restablecer progreso',freePlan:'Plan gratuito',premium:'Premium',noAds:'Sin anuncios',extendedAI:'Tutor de IA avanzado',offline:'Aprendizaje sin conexión',statistics:'Estadísticas avanzadas',competitions:'Competiciones',leaderboard:'Clasificación',achievements:'Logros',chooseLanguages:'Elige tus idiomas',interfaceHint:'La interfaz usa el idioma elegido.',nativeHint:'Las explicaciones y traducciones usan este idioma.',learningHint:'Las lecciones y ejercicios usan este idioma.',startLearning:'Empezar a aprender',global:'Una app — todo el mundo',noAccount:'Empieza de inmediato. La cuenta solo es necesaria para sincronización y competiciones.',freeForever:'El aprendizaje básico sigue siendo gratis.',chatPlaceholder:'Escribe en el idioma de aprendizaje...'}
};

function normalize(code){return String(code||'').toLowerCase().split('-')[0];}
export function detectInterfaceLanguage(){const device=normalize(typeof navigator!=='undefined'?navigator.language:'en');return LANGUAGE_CATALOG.some(l=>l.code===device)?device:'en';}
export function t(code,key){const lang=normalize(code);return DICT[lang]?.[key] ?? EN[key] ?? key;}
export function hasLocale(code){return Boolean(DICT[normalize(code)]);}
export { DICT };
