import React,{useEffect,useMemo,useState} from 'react';
import {BookOpen,Flame,User,Home as HomeIcon,ChevronRight,Check,X,Volume2,Star,RotateCcw,Brain,Settings,Globe2,Trophy,LogIn} from 'lucide-react';
import './styles.css';
import {DEFAULT_SOURCE,DEFAULT_TARGET} from './data/courses';
import {LANGUAGE_CATALOG,getAudioLanguage,language,MEGA_LESSON_COUNT,getVirtualLesson,getCurriculumStats,translateWord} from './engine/course-engine';
import {detectInterfaceLanguage,t} from './i18n';

const STORAGE='english-ai-global-state-v2';
const PREFS='english-ai-global-prefs-v2';
const LEGACY='english-ai-mega-state';
const PAIR=(source,target)=>`${source}->${target}`;
const baseProgress=()=>({xp:0,streak:0,lastDay:null,completed:[],level:1,mistakes:0,mastery:{}});
const defaultPrefs=()=>({interfaceLanguage:detectInterfaceLanguage(),nativeLanguage:localStorage.getItem('english-ai-source')||DEFAULT_SOURCE,learningLanguage:localStorage.getItem('english-ai-target')||DEFAULT_TARGET,setupDone:false});
function readJSON(key,fallback){try{return {...fallback,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return fallback}}
function readApp(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'{}');return {profiles:raw.profiles||{},createdAt:raw.createdAt||Date.now()}}catch{return {profiles:{},createdAt:Date.now()}}}
function readLegacy(){try{return JSON.parse(localStorage.getItem(LEGACY)||'null')}catch{return null}}
function saveApp(app){localStorage.setItem(STORAGE,JSON.stringify(app))}
function speak(text,code){const value=String(text||'').trim();if(!value||!window.speechSynthesis)return;const u=new SpeechSynthesisUtterance(value);u.lang=getAudioLanguage(value,code);u.rate=.9;window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}
function AudioButton({text,code='en',small=false}){const value=String(text||'').trim();if(!value)return null;return <button type="button" className={`speak-icon ${small?'small':''}`} aria-label={`Прослухати ${value}`} onClick={e=>{e.stopPropagation();speak(value,code)}}><Volume2 size={small?16:18}/></button>}
function pairForOption(text,source,target){const value=String(text||'');const sourceText=translateWord(value,target,source);const targetText=translateWord(value,source,target);const sourceIsExact=sourceText!==value||targetText===value;return sourceIsExact?{sourceText,targetText}:{sourceText:value,targetText:translateWord(value,source,target)}}
function QuestionText({q,source,target}){const sourceText=String(q.sourceText||'').trim();const targetText=String(q.targetText||'').trim();const fallback=String(q.q||'').trim();if(!sourceText&&!targetText&&!fallback)return null;const first=sourceText||fallback;return <div className="question-lines">{first&&<div className="language-line"><span>{source.toUpperCase()}</span><b>{first}</b><AudioButton text={first} code={source}/></div>}{targetText&&<div className="language-line"><span>{target.toUpperCase()}</span><b>{targetText}</b><AudioButton text={targetText} code={target}/></div>}</div>}
function AnswerText({value,source,target,answered,correct}){const raw=String(value||'');if(!raw)return null;if(raw.includes(' — ')){const [t,s]=raw.split(' — ');return <div className="answer-language"><div className="language-line"><span>{target.toUpperCase()}</span><b>{t}</b><AudioButton text={t} code={target} small/></div><div className="language-line"><span>{source.toUpperCase()}</span><b>{s}</b><AudioButton text={s} code={source} small/></div></div>}
 const sourceText=source==='uk'?translateWord(raw,target,source):translateWord(raw,target,source);
 const targetText=translateWord(raw,source,target);
 const visible=sourceText===raw?targetText:sourceText===raw?targetText:targetText;
 const hidden=sourceText===raw?raw:sourceText;
 const visibleCode=target;
 const hiddenCode=source;
 const [revealed,setRevealed]=useState(false);
 return <div className="answer-language"><div className="language-line"><span className={revealed?'':'hint-label'}>{revealed?source.toUpperCase():'Підказка'}</span>{revealed?<><b>{hidden}</b><AudioButton text={hidden} code={hiddenCode} small/></>:null}</div><div className="language-line"><span>{target.toUpperCase()}</span><b>{visible}</b><AudioButton text={visible} code={visibleCode} small/></div>{!revealed&&<button type="button" className="hint-click" onClick={e=>{e.stopPropagation();setRevealed(true)}}>Підказка</button>}</div>}

export default function MegaApp(){
 const [prefs,setPrefs]=useState(()=>readJSON(PREFS,defaultPrefs()));
 const [app,setApp]=useState(()=>readApp());
 const [screen,setScreen]=useState(()=>prefs.setupDone?'home':'setup');
 const [lesson,setLesson]=useState(null);const [questionIndex,setQuestionIndex]=useState(0);const [selected,setSelected]=useState(null);const [answered,setAnswered]=useState(false);const [score,setScore]=useState(0);const [number,setNumber]=useState(1);const [toast,setToast]=useState('');
 const source=prefs.nativeLanguage,target=prefs.learningLanguage;const pair=PAIR(source,target);const state=app.profiles[pair]||baseProgress();const ui=key=>t(prefs.interfaceLanguage,key);
 useEffect(()=>{localStorage.setItem(PREFS,JSON.stringify(prefs));localStorage.setItem('english-ai-source',source);localStorage.setItem('english-ai-target',target)},[prefs,source,target]);
 useEffect(()=>{if(!app.profiles[pair]){setApp(a=>({...a,profiles:{...a.profiles,[pair]:baseProgress()}}));return}const today=new Date().toDateString();if(state.lastDay===today)return;const yesterday=new Date(Date.now()-86400000).toDateString();const next={...state,lastDay:today,streak:state.lastDay===yesterday?state.streak+1:state.lastDay?1:0};setApp(a=>({...a,profiles:{...a.profiles,[pair]:next}}))},[pair]);
 useEffect(()=>{saveApp(app)},[app]);
 const notify=x=>{setToast(x);setTimeout(()=>setToast(''),1600)};
 const updateProgress=fn=>setApp(a=>({...a,profiles:{...a.profiles,[pair]:fn(a.profiles[pair]||baseProgress())}}));
 const changePrefs=patch=>setPrefs(p=>({...p,...patch}));
 const openLesson=n=>{const id=Math.max(1,Math.min(MEGA_LESSON_COUNT,Math.floor(Number(n)||1)));setLesson(getVirtualLesson(id,source,target));setNumber(id);setQuestionIndex(0);setSelected(null);setAnswered(false);setScore(0);setScreen('lesson')};
 const choose=o=>{if(answered)return;const q=lesson.questions[questionIndex];setSelected(o);setAnswered(true);if(o===q.answer){setScore(v=>v+1);notify(ui('correct'))}else{updateProgress(s=>({...s,mistakes:s.mistakes+1}));notify(ui('almost'))}};
 const next=()=>{if(questionIndex<lesson.questions.length-1){setQuestionIndex(i=>i+1);setSelected(null);setAnswered(false)}else finish()};
 const finish=()=>{const total=lesson.questions.length;const gain=lesson.xp+score*5;const accuracy=total?score/total:0;updateProgress(s=>{const mastery={...s.mastery,[lesson.id]:Math.round(accuracy*100)};return {...s,xp:s.xp+gain,level:Math.floor((s.xp+gain)/100)+1,completed:[...new Set([...s.completed,lesson.id])],mastery}});setScreen('result')};
 const reset=()=>{if(!window.confirm('Reset progress for this language pair?'))return;updateProgress(()=>baseProgress());notify('Progress reset')};
 if(screen==='setup')return <Setup prefs={prefs} change={changePrefs} done={()=>{changePrefs({setupDone:true});setScreen('home')}} ui={ui}/>;
 if(screen==='lesson')return <Lesson lesson={lesson} questionIndex={questionIndex} selected={selected} answered={answered} score={score} choose={choose} next={next} exit={()=>setScreen('home')} ui={ui} target={target} source={source}/>;
 if(screen==='result')return <Result lesson={lesson} score={score} state={state} home={()=>setScreen('home')} again={()=>openLesson(number)} ui={ui}/>;
 return <div className="app"><Header state={state} source={source} target={target} languages={()=>setScreen('languages')} ui={ui}/><main>
   {screen==='home'&&<Home state={state} source={source} target={target} openLesson={openLesson} courses={()=>setScreen('courses')} ai={()=>setScreen('ai')} ui={ui}/>} 
   {screen==='courses'&&<Courses state={state} openLesson={openLesson} number={number} setNumber={setNumber} ui={ui}/>} 
   {screen==='languages'&&<Languages prefs={prefs} change={changePrefs} ui={ui}/>} 
   {screen==='profile'&&<Profile state={state} reset={reset} ui={ui}/>} 
   {screen==='ai'&&<AI ui={ui}/>} 
 </main>{toast&&<div className="toast">{toast}</div>}<nav className="bottom"><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}><HomeIcon/><span>{ui('home')}</span></button><button className={screen==='courses'?'active':''} onClick={()=>setScreen('courses')}><BookOpen/><span>{ui('course')}</span></button><button className={screen==='ai'?'active':''} onClick={()=>setScreen('ai')}><Brain/><span>{ui('ai')}</span></button><button className={screen==='profile'?'active':''} onClick={()=>setScreen('profile')}><User/><span>{ui('profile')}</span></button></nav></div>
}

function Setup({prefs,change,done,ui}){return <div className="app setup-app"><main className="page setup"><div className="hero"><div><p className="eyebrow">GLOBAL LANGUAGE ENGINE</p><h1>{ui('global')}</h1><p>{ui('noAccount')}</p></div><div className="hero-icon">🌍</div></div><div className="card"><h2><Globe2/> {ui('chooseLanguages')}</h2><label>{ui('interfaceLanguage')}</label><select value={prefs.interfaceLanguage} onChange={e=>change({interfaceLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><p className="muted">{ui('interfaceHint')}</p><label>{ui('nativeLanguage')}</label><select value={prefs.nativeLanguage} onChange={e=>change({nativeLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><p className="muted">{ui('nativeHint')}</p><label>{ui('learningLanguage')}</label><select value={prefs.learningLanguage} onChange={e=>change({learningLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><p className="muted">{ui('learningHint')}</p><button className="continue" onClick={done}>{ui('startLearning')} <ChevronRight/></button></div><div className="card"><b>🆓 {ui('freeLearning')}</b><p>{ui('withoutRegistration')}</p></div></main></div>}
function Header({state,source,target,languages,ui}){return <header><div className="brand"><div className="logo">E</div><strong>English AI</strong></div><div className="stats"><button className="language-pill" onClick={languages}>{language(source).flag} → {language(target).flag}</button><span>🔥 {state.streak}</span><span>⭐ {state.xp}</span></div></header>}
function Home({state,source,target,openLesson,courses,ai,ui}){const s=getCurriculumStats();return <div className="page"><section className="hero"><div><p className="eyebrow">{language(source).name.toUpperCase()} → {language(target).name.toUpperCase()}</p><h1>English AI 🚀</h1><p>{ui('allLevels')}. {s.lessonCount.toLocaleString('en-US')} {ui('lessons')}. {ui('freeForever')}</p></div><div className="hero-icon">🦉</div></section><div className="goal card"><div className="goal-top"><b>{ui('course')}</b><span>{s.lessonCount.toLocaleString('en-US')} {ui('lessons')}</span></div><p>4 exercises: vocabulary, retrieval, grammar and context.</p></div><div className="level-grid">{s.levels.map((x,i)=><button className="level-chip" key={x.level} onClick={()=>openLesson(Math.floor(i*MEGA_LESSON_COUNT/6)+1)}><b>{x.level}</b><span>{Math.floor(MEGA_LESSON_COUNT/6).toLocaleString('en-US')} {ui('lessons')}</span></button>)}</div><div className="section-title"><h2>{ui('start')}</h2></div><div className="path">{[1,2,3,4,5].map(n=><LessonCard key={n} lesson={getVirtualLesson(n,source,target)} state={state} openLesson={openLesson} ui={ui}/>)}</div><button className="continue" onClick={courses}>{ui('course')} <ChevronRight/></button><button className="ai-banner" onClick={ai}><div className="ai-face">🤖</div><div><b>{ui('aiTutor')}</b><p>{ui('practice')}</p></div><ChevronRight/></button></div>}
function LessonCard({lesson,state,openLesson,ui}){const done=state.completed.includes(lesson.id);return <button className={`lesson-card ${done?'done':''}`} onClick={()=>openLesson(lesson.number)}><div className="lesson-icon">{done?<Check size={25}/>:lesson.icon}</div><div><small>{lesson.unit}</small><h3>{lesson.title}</h3><span>{lesson.xp} XP · {ui('free')}</span></div><ChevronRight/></button>}
function Courses({state,openLesson,number,setNumber,ui}){return <div className="page"><p className="eyebrow">MEGA CURRICULUM</p><h1>{ui('allLevels')}</h1><div className="card"><h2>{ui('lesson')}</h2><p>1–2,000,000,000.</p><input type="number" min="1" max={MEGA_LESSON_COUNT} value={number} onChange={e=>setNumber(Math.max(1,Math.min(MEGA_LESSON_COUNT,Number(e.target.value)||1)))}/><button className="continue" onClick={()=>openLesson(number)}>#{Number(number).toLocaleString('en-US')} <ChevronRight/></button></div><div className="level-grid">{['A1','A2','B1','B2','C1','C2'].map((l,i)=><button className="level-chip" key={l} onClick={()=>openLesson(Math.floor(i*MEGA_LESSON_COUNT/6)+1)}><b>{l}</b><span>{ui('free')}</span></button>)}</div><p className="muted">{ui('completed')}: {state.completed.length} · XP: {state.xp}</p></div>}
function Languages({prefs,change,ui}){return <div className="page"><p className="eyebrow">LANGUAGE ENGINE</p><h1>{ui('languages')}</h1><div className="card"><h2><Settings/> {ui('settings')}</h2><label>{ui('interfaceLanguage')}</label><select value={prefs.interfaceLanguage} onChange={e=>change({interfaceLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><label>{ui('nativeLanguage')}</label><select value={prefs.nativeLanguage} onChange={e=>change({nativeLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><label>{ui('learningLanguage')}</label><select value={prefs.learningLanguage} onChange={e=>change({learningLanguage:e.target.value})}>{LANGUAGE_CATALOG.map(l=><option key={l.code} value={l.code}>{l.flag} {l.name}</option>)}</select><p className="muted">{ui('nativeHint')} {ui('learningHint')}</p></div><div className="card"><b>{ui('withoutRegistration')}</b><p>{ui('noAccount')}</p></div></div>}
function Lesson({lesson,questionIndex,selected,answered,score,choose,next,exit,ui,target,source}){const q=lesson.questions[questionIndex];const pct=Math.round(((questionIndex+(answered?1:0))/lesson.questions.length)*100);return <div className="lesson-screen"><div className="lesson-top"><button onClick={exit}><X/></button><div className="progress"><i style={{width:`${Math.max(8,pct)}%`}}/></div><span>{questionIndex+1}/{lesson.questions.length}</span></div><div className="question"><div className="q-meta">{lesson.level} · {ui('lesson')} #{lesson.number.toLocaleString('en-US')} · {q.skill}</div><QuestionText q={q} source={source} target={target}/><div className="answers">{q.options.map(o=><AnswerButton key={o} value={o} q={q} source={source} target={target} answered={answered} selected={selected} choose={choose}/>)}</div></div>{answered&&<div className={`feedback ${selected===q.answer?'good':'bad'}`}><b>{selected===q.answer?ui('great'):ui('almost')}</b><span>{selected===q.answer?ui('correct'):`${ui('rightAnswer')}: ${q.answer}`}</span>{selected!==q.answer&&q.targetText&&<AudioButton text={q.targetText} code={source}/>}</div>}<button className="continue" disabled={!answered} onClick={next}>{questionIndex<lesson.questions.length-1?ui('next'):ui('finish')} <ChevronRight/></button><p className="muted">{ui('correct')}: {score}/{questionIndex+(answered?1:0)}</p></div>}
function AnswerButton({value,q,source,target,answered,selected,choose}){const [revealed,setRevealed]=useState(false);useEffect(()=>setRevealed(false),[q?.q,value]);const isCorrect=value===q.answer;const isWrong=answered&&selected===value&&!isCorrect;const raw=String(value||'');if(raw.includes(' — ')){const [targetText,sourceText]=raw.split(' — ');return <button className={`answer-card ${answered&&isCorrect?'correct':''} ${isWrong?'wrong':''}`} disabled={answered} onClick={()=>choose(value)}><div className="answer-language"><div className="language-line"><span>{target.toUpperCase()}</span><b>{targetText}</b><AudioButton text={targetText} code={target} small/></div><div className="language-line"><span>{source.toUpperCase()}</span><b>{sourceText}</b><AudioButton text={sourceText} code={source} small/></div></div>{answered&&isCorrect?<Check className="answer-status"/>:isWrong?<X className="answer-status"/>:null}</button>}
 const sourceText=translateWord(raw,target,source);const targetText=translateWord(raw,source,target);const hiddenText=sourceText===raw?raw:sourceText;const visibleText=sourceText===raw?targetText:targetText;return <button className={`answer-card ${answered&&isCorrect?'correct':''} ${isWrong?'wrong':''}`} disabled={answered} onClick={()=>choose(value)}><div className="answer-language"><div className="language-line"><span>{target.toUpperCase()}</span><b>{visibleText}</b><AudioButton text={visibleText} code={target} small/></div><div className="language-line"><button type="button" className={`hint-click ${revealed?'revealed':''}`} onClick={e=>{e.stopPropagation();setRevealed(true)}}>{revealed?<><span>{source.toUpperCase()}</span><b>{hiddenText}</b><AudioButton text={hiddenText} code={source} small/></>:<b>Підказка</b>}</button></div></div>{answered&&isCorrect?<Check className="answer-status"/>:isWrong?<X className="answer-status"/>:null}</button>}
function Result({lesson,score,state,home,again,ui}){const total=lesson.questions.length;const accuracy=Math.round(score/total*100);return <div className="result"><div className="confetti">🎉</div><p className="eyebrow">{ui('finish').toUpperCase()}</p><h1>{accuracy>=75?ui('great'):ui('completed')}</h1><p>#{lesson.number.toLocaleString('en-US')} · {lesson.level}</p><div className="result-grid"><div><Star/><b>+{lesson.xp+score*5}</b><span>XP</span></div><div><Check/><b>{score}/{total}</b><span>{accuracy}%</span></div><div><Flame/><b>{state.streak}</b><span>{ui('streak')}</span></div></div><button className="continue" onClick={home}>{ui('continue')} <ChevronRight/></button><button className="secondary" onClick={again}><RotateCcw/> {ui('start')}</button></div>}
function Profile({state,reset,ui}){return <div className="page"><p className="eyebrow">{ui('profile').toUpperCase()}</p><h1>{ui('progress')}</h1><div className="stats-grid"><div><b>{state.xp}</b><span>XP</span></div><div><b>{state.streak}</b><span>{ui('streak')}</span></div><div><b>{state.completed.length}</b><span>{ui('completed')}</span></div><div><b>{state.mistakes}</b><span>{ui('mistakes')}</span></div></div><div className="card"><h2>🆓 {ui('freePlan')}</h2><p>{ui('freeLearning')}.</p></div><div className="card"><h2>👑 {ui('premium')}</h2><p>{ui('noAds')} · {ui('extendedAI')} · {ui('offline')} · {ui('statistics')}</p></div><div className="card"><h2><Trophy/> {ui('competitions')}</h2><p>{ui('leaderboard')} · {ui('achievements')}</p><p className="muted">Account is optional and can be added later for cloud sync and global competition.</p></div><button className="danger" onClick={reset}>{ui('reset')}</button></div>}
function AI({ui}){const [messages,setMessages]=useState([{r:'ai',t:'Hi! 👋 Tell me about your day in English.'}]);const [v,setV]=useState('');const send=()=>{if(!v.trim())return;const x=v.trim();setMessages(m=>[...m,{r:'user',t:x},{r:'ai',t:`Good job! 👍 Keep going with: “${x.replace(/\.$/,'')}.”`}]);setV('')};return <div className="page ai-page"><div className="ai-header"><div className="ai-face">🤖</div><div><p className="eyebrow">{ui('aiTutor').toUpperCase()}</p><h1>English Chat</h1></div></div><div className="chat">{messages.map((m,i)=><div key={i} className={`bubble ${m.r}`}>{m.t}</div>)}</div><div className="chat-input"><input value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={ui('chatPlaceholder')}/><button onClick={send}>➤</button></div></div>}